apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/conforma/crds/config/crd?ref=6f685d079f1991c801d39d011b74ffa9c1fb09e3
  - ns.yaml
  - public-ecp-rbac.yaml

namespace: enterprise-contract-service

generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: ec-defaults
    namespace: enterprise-contract-service
    literals:
      - verify_ec_task_bundle=quay.io/enterprise-contract/ec-task-bundle@sha256:248b12483e5babf95a0c936e086b0fa354160d9c5c940bdfb7585440fa3e0769
      - verify_ec_task_git_url=https://github.com/enterprise-contract/ec-cli.git
      - verify_ec_task_git_revision=b345847182602d9a5ce9e957fa76fe02575c8018
      - verify_ec_task_git_pathInRepo=tasks/verify-enterprise-contract/0.1/verify-enterprise-contract.yaml

patches:
  - target:
      group: console.openshift.io
      version: v1
      kind: ConsoleYAMLSample
      name: ecp-example
    path: remove-ecp-example.yaml
