apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-appstudio/internal-services/config/crd?ref=8e956135a548dfcc50d0d005cac576ff15bc426f

namespace: release-service
